# Generated by Django 5.2.6 on 2025-09-08 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News', #sudah diganti menjadi 'Cleats' di migrasi kedua
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('brand', models.CharField(max_length=70)),
                ('size', models.IntegerField(default=0)),
                ('price', models.IntegerField(default=0)),
                ('stock', models.IntegerField(default=0)),
                ('rating', models.FloatField(default=0.0)),
                ('description', models.TextField()),
                ('thumbnail', models.URLField(blank=True, null=True)),
                ('category', models.CharField(choices=[('FG', 'Firm Ground'), ('AG', 'Artificial Grass'), ('MG', 'Multi Ground'), ('turf', 'Turf'), ('indoor', 'Indoor')], default='MG', max_length=25)),
                ('is_featured', models.BooleanField(default=False)),
            ],
        ),
    ]
