# Generated by Django 5.2.6 on 2025-09-14 14:21

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rename_news_cleats'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cleats',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
