# Generated by Django 5.2.6 on 2025-09-22 03:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_cleats_id'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cleats',
            new_name='Product',
        ),
    ]
